@startuml dhifa_collection

Entity users {
    * email: VARCHAR(30) <<PK>>
    --
    * password: VARCHAR(30)
    * fullname: VARHCAR(100)
    * address: VARHCAR(200)
    * phone_number: VARHCAR(50)
}

Entity products {
    * id_product: INT(11) AI <<PK>>
    --
    * name: VARCHAR(100)
    * price: BIGINT
    * qty: INT(11)
}

Entity orders {
    * order_id: VARCHAR(50) <<PK>> <<FK>>
    --
    * email: VARCHAR(30) <<PK>> <<FK>>
    * total: BIGINT
    * status: ENUM("Open", "Close")
}

Entity order_detail {
    * id_order: INT(11) <<PK>>
    --
    * product_id: INT(11) <<FK>>
    * price: INT(11)
    * qty: INT(11)
    * amount: INT(11)
}

users |o--o{ orders: memiliki
orders ||--o{ order_detail: memiliki
order_detail ||--|{ products: memiliki

@enduml